config/routes.rb
Rails.application.routes.draw do
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/home' => "application#home"
  post '/courses/:course_id/add' => "seats#add"
  delete '/courses/:course_id/drop' => "seats#drop"
  get 'students/:id/courses' => "students#courses"
  post 'students/:followed_student_id/follow' => "relationships#follow"
  delete 'students/:followed_student_id/unfollow' => "relationships#unfollow"

  resources :students, only: [:new, :create, :show, :index]
  resources :courses, only: [:show, :index]
  resources :teachers, only: [:show, :index]
  resources :seats


  root 'application#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :seats
  has_many :students, through: :seats
  belongs_to :teacher
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :student
  belongs_to :followed_student, class_name: 'Student'



  # validate :realism
  #
  #  private
  #
  #  def realism
  #    return unless user_id == followed_user_id
  #    errors.add :user, 'You can't follow yourself, douchebag.'
  #  end


end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password

  has_many :seats
  has_many :courses, through: :seats

  has_many :relationships
  has_many :followed_students, through: :relationships

  has_many :followers, foreign_key: :followed_student_id, class_name: 'Relationship'
  has_many :follower_students, through: :followers, source: :student

  validates :username, uniqueness: true
  validates :username, presence: true
  validates :name, presence: true

  def following?
    self.followed_students.count
  end

  def followers?
    self.follower_students.count
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
  end

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_student
  end

  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def home
    @student = current_student
  end

  helper_method :current_student #this is required to use this method in my views

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authentication_required, only: [:index, :show]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @enrolled = current_student.courses.include?(@course)
  end




end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def follow
    me = Student.find(session[:student_id])
    friend = Student.find(params[:followed_student_id])

    Relationship.create(student_id: me.id, followed_student_id: friend.id)  

    redirect_to student_path(friend)
  end

  def unfollow
    me = Student.find(session[:student_id])
    friend = Student.find(params[:followed_student_id])

    Relationship.find_by(student_id: me.id, followed_student_id: friend.id).delete

    redirect_to student_path(friend)
  end

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController

  def add
    student_id = session[:student_id]
    course_id = params[:course_id]
    Seat.create(student_id: student_id, course_id: course_id)

    redirect_to '/home'
  end

  def drop
    seat = Seat.find_by(course_id: params[:course_id], student_id: session[:student_id])
    if seat
      seat.destroy

      redirect_to '/home'
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    student = Student.find_by(username: params[:username])
    if student && student.authenticate(params[:password])
      session[:student_id] = student.id

      redirect_to '/home'
    else
      render 'sessions/new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end




# if session[:user_id]
#   @student = Student.find(id: session[:user_id] )
#   redirect_to student_path(@student)
# else
#   render :new
# end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authentication_required, only: [:show]

  def new
    @student = Student.new
  end

  def create
    @student = Student.new
    @student.name = params[:student][:name]
    @student.username = params[:student][:username]
    @student.password = params[:student][:password]
    if @student.save
      session[:student_id] = @student.id
      redirect_to student_path(@student)
    else
      render 'students/new'
    end
  end

  def show
    @student = Student.find(params[:id])
    @me = Student.find(session[:student_id])
    @follower = @student.follower_students.include?(@me)
  end

  def index
    @students = Student.all
  end

  def courses
    @student = Student.find(params[:id])
  end

  #
  # private
  #
  # def student_params
  #     params.require(:student).permit(:name, :username)
  # end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def show
    @teacher = Teacher.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/application/home.html.erb
<h1 class="ui inverted header"><%= @student.name %></h1>
  <div class="ui compact segments">
    <div class="ui compact segment">
      <p><%= link_to "View all courses", courses_path%></p>
    </div>
    <div class="ui compact segment">
      <p><%= link_to "View my Schedule", "students/#{@student.id}/courses" %></p>
    </div>
    <div class="ui compact segment">
      <p><%= link_to "View all students", students_path %></p>
    </div>
    <div class="ui compact segment">
      <p><%= link_to "Logout", logout_path %></p>
    </div>
  </div>
  <p class="footer">You are logged in as <%= current_student.name %></p>

app/views/application/index.html.erb
<h1>Welcome to Student Link! </h1>
<h3>What would you like to do today?</h3>
<%= link_to "Sign up?", new_student_path %>
<h2>OR</h2>
<%= link_to "Log In?", login_path %>

app/views/courses/index.html.erb
<h1 class='ui green header'>Check out all available courses!</h1>

  <% @courses.each do |course| %>
  <h3><%= link_to "#{course[:title]}", course_path(course), class: 'ui button' %></h3>
  <% end %>
  <p class="home"><%= link_to "Home", "/home" %></p>
  <p class="footer">You are logged in as <%= current_student.name %></p>

app/views/courses/show.html.erb
<h1>Welcome to <%= @course[:title] %></h1>
<h3>Course Instructor: <%= link_to "#{@course.teacher[:name]}", teacher_path(@course.teacher) %> </h3>
<h3>Course Description: </h3>
<p><%="#{@course.description}" %></p>
<br>
<% if @enrolled %>
  <%= button_to "Drop this course?", "/courses/#{@course.id}/drop", method: :delete %>
<% else %>
  <%= button_to "Join this course?", "/courses/#{@course.id}/add", method: :post %>
<% end %>
<p class="home"><%= link_to "Home", "/home" %></p>
<p class="footer">You are logged in as <%= current_student.name %></p>

app/views/students/courses.html.erb
<h1>My Schedule</h1>
<br>
<% @student.courses.each do |course|%>
<p><%= link_to "#{course.title}", course_path(course) %></p>
<% end %>
<br>
<br>
<br>
<br>
<p><%= link_to "Home", "/home" %></p>
<p class="footer">You are logged in as <%= current_student.name %></p>

app/views/students/index.html.erb
<h1>Here are all your classmates!</h1>

<% @students.each do |student| %>
<p><%= link_to "#{student.name}", student_path(student) %></p>
<% end %>

app/views/students/new.html.erb
<h1>Sign up for Student Link here!</h1>

<%= form_for(@student) do |f| %>
  <p>Name: <%= f.text_field :name %></p>
  <p>Username: <%= f.text_field :username %></p>
  <p>Password: <%= f.password_field :password %></p>
  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1><%= "#{@student.name}"%></h1>
<% if @follower %>
<p>You follow this user</p>
<% end %>
<p>Following: <%= @student.following? %> </p>
<p>Followers: <%= @student.followers? %> </p>


  <% if @follower %>
    <%= button_to "Unfollow #{@student.name}", "/students/#{@student.id}/unfollow", method: :delete, class: 'ui button'%>
  <% elsif @student == @me%>
    <h3>You can't follow yourself, douche.</h3>
  <% else %>
    <%= button_to "Follow #{@student.name}", "/students/#{@student.id}/follow", method: :post, class: 'ui button'%>
  <% end %>

<br>
<br>
<%= link_to "View all students", students_path %>
<br>
<br>

<br>
<br>
<%= link_to "Logout", logout_path %>
<br>
<br>
<br>
<br>
<p><%= link_to "Home", "/home" %></p>
<p class="footer">You are logged in as <%= current_student.name %></p>

app/views/teachers/show.html.erb
<h1><%= "#{@teacher[:name]}" %></h1>